export { TableScene } from './scene.js';
export { DiceOnTable, percentileSpec } from './dice-on-table.js';
export type { TableRollResult } from './dice-on-table.js';
export type { SceneOptions } from './scene.js';
export type { ViewName } from './viewpoints.js';
export { buildTable, TABLE } from './table.js';
export { BULB, VIEWS, SPOTS, SIZES, projectToFrame, resolveView, layoutFor } from './viewpoints.js';
export type { Viewpoint, Layout } from './viewpoints.js';
export type { Hotspot, TableParts } from './table.js';
export { applyPS1, RetroPipeline, INTERNAL_LONG } from './ps1.js';
export { woodTexture, paperTexture, matTexture, metalTexture } from './textures.js';
