export { POLYHEDRA, validate, faceNormal, faceCentroid } from './polyhedra.js';
export type { Polyhedron, Vec3, ValidationIssue } from './polyhedra.js';
export { simulate, topFaceOf, mulberry32, trayHalfFor } from './simulate.js';
export type { SimResult, SimOptions, DieFrame, Degeneracy } from './simulate.js';
export { labelFaces, readTopValue, faceValuesFor, splitPercentile, joinPercentile } from './label.js';
export type { LabelOptions } from './label.js';
export { buildDiceGeometry, circumradius } from './geometry.js';
export { buildNumberAtlas } from './texture.js';
export { DiceRenderer, percentileDice } from './renderer.js';
export type { DieSpec, RollOptions, RendererDiagnostics } from './renderer.js';
