export { POLYHEDRA, validate, faceNormal, faceCentroid } from './polyhedra.js';
export type { Polyhedron, Vec3, ValidationIssue } from './polyhedra.js';
export { simulate, topFaceOf, mulberry32, trayHalfFor, readTrack } from './simulate.js';
export type { SimResult, SimOptions, DieTrack, Degeneracy } from './simulate.js';
export { labelFaces, readTopValue, faceValuesFor, splitPercentile, joinPercentile } from './label.js';
export type { LabelOptions } from './label.js';
export { buildDiceGeometry, circumradius } from './geometry.js';
export { buildNumberAtlas, ensureDiceFont } from './texture.js';
export { DiceRenderer, percentileDice } from './renderer.js';
export { applyDiceNumbering, setDiceUniform, createDiceMaterial } from './material.js';
export type { DiceUniforms, UniformName } from './material.js';
export type { DieSpec, RollOptions, RendererDiagnostics } from './renderer.js';
