import type { CatalogItem } from './types.js';

/**
 * Catálogo de itens, página 6 do PDF.
 *
 * GERADO por extração geométrica de coluna (`pdftotext -layout -x/-y/-W/-H`),
 * não transcrito à mão. A extração ingênua misturava as colunas de Remédios e
 * Equipamentos e foi o que produziu os preços errados relatados antes em S14.
 *
 * A coluna do PDF chama-se PESO; a área de inventário da ficha chama ESPAÇOS.
 * Ver S8 — aqui é exposta como `peso` e consumida como espaço ocupado.
 */
export const CATALOGO: CatalogItem[] = [
  { nome: 'AGOMELATINA (VALDOXAN)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 752.61, peso: null },
  { nome: 'ALPRAZOLAM (FRONTAL/XANAX)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 78.95, peso: null },
  { nome: 'AMITRIPTILINA', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 52.63, peso: null },
  { nome: 'BUPROPIONA (WELLBUTRIN)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 236.84, peso: null },
  { nome: 'CLONAZEPAM (RIVOTRIL)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 65.79, peso: null },
  { nome: 'DIAZEPAM (VALIUM)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 39.47, peso: null },
  { nome: 'FLUOXETINA (PROZAC)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 131.58, peso: null },
  { nome: 'MELATONINA', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 78.95, peso: null },
  { nome: 'SERTRALINA (ZOLOFT)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 105.26, peso: null },
  { nome: 'TRAZODONA', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 184.21, peso: null },
  { nome: 'VENLAFAXINA (EFEXOR)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 315.79, peso: null },
  { nome: 'HALOPERIDOL (HALDOL) PARA CO', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 131.58, peso: null },
  { nome: 'OLANZAPINA (ZYPREXA)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 526.32, peso: null },
  { nome: 'QUETIAPINA (SEROQUEL)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 394.74, peso: null },
  { nome: 'RISPERIDONA (RISPERDAL)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 263.16, peso: null },
  { nome: 'ZOLPIDEM (STILNOX)', grupo: 'TRANSTORNOS PSICOLÓGICOS', categoria: 'remedio', preco: 157.89, peso: null },
  { nome: 'BACLOFENO', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 210.53, peso: null },
  { nome: 'DIPIRONA', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 26.32, peso: null },
  { nome: 'GABAPENTINA', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 236.84, peso: null },
  { nome: 'IBUPROFENO', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 21.05, peso: null },
  { nome: 'LEVODOPA (PARKINSON)', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 315.79, peso: null },
  { nome: 'MORFINA SINTÉTICA (HEROÍNA)', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 789.47, peso: null },
  { nome: 'PREGABALINA (LYRICA)', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 526.32, peso: null },
  { nome: 'TRAMADOL', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 131.58, peso: null },
  { nome: 'CODEÍNA', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 184.21, peso: null },
  { nome: '6-APB (6-(2-AMINOPROPIL)BENZOFURAN)', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 526.32, peso: null },
  { nome: 'CORTICOSTEROIDES (PREDNISONA)', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 105.26, peso: null },
  { nome: 'IMUNOSSUPRESSORES (AZATIOPRINA)', grupo: 'DOENÇAS NEUROLÓGICAS E FÍSICAS', categoria: 'remedio', preco: 657.89, peso: null },
  { nome: 'AMOXICILINA', grupo: 'INFECÇÕES, FERIMENTOS E SUPORTE MÉDICO', categoria: 'remedio', preco: 78.95, peso: null },
  { nome: 'CIPROFLOXACINO', grupo: 'INFECÇÕES, FERIMENTOS E SUPORTE MÉDICO', categoria: 'remedio', preco: 131.58, peso: null },
  { nome: 'VANCOMICINA', grupo: 'INFECÇÕES, FERIMENTOS E SUPORTE MÉDICO', categoria: 'remedio', preco: 394.74, peso: null },
  { nome: 'KIT DE PRIMEIROS SOCORROS', grupo: 'MEDKIT', categoria: 'remedio', preco: 100.0, peso: null },
  { nome: 'KIT MEDICINA AVANÇADA', grupo: 'MEDKIT', categoria: 'remedio', preco: 300.0, peso: null },
  { nome: 'CORDA (10 METROS)', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 58.95, peso: 3 },
  { nome: 'LANTERNA', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 13.16, peso: 3 },
  { nome: 'WALKIE-TALKIE', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 115.79, peso: 2 },
  { nome: 'PANO MULTIUSO', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 26.32, peso: 2 },
  { nome: 'BÍBLIA', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 0.0, peso: 3 },
  { nome: 'MAPA', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 100.32, peso: 2 },
  { nome: 'BASTÃO DE CAMINHADA', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 53.16, peso: 8 },
  { nome: 'LANTERNA UV LUZ NEGRA', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 23.16, peso: 3 },
  { nome: 'LUPA', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 8.26, peso: 2 },
  { nome: 'BLOCO DE NOTAS', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 50.34, peso: 3 },
  { nome: 'CANETA AZUL', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 5.0, peso: 1 },
  { nome: 'CANETA PRETA', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 10.0, peso: 1 },
  { nome: 'CANETA VERMELHA', grupo: 'BÁSICOS', categoria: 'equipamento', preco: 5.0, peso: 1 },
  { nome: 'KARAMBIT', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 126.32, peso: 4 },
  { nome: 'FACA TÁTICA', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 113.16, peso: 4 },
  { nome: 'MINI FACA', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 60.5, peso: 3 },
  { nome: 'ANEL LÂMINA SECRETA', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 39.47, peso: 1 },
  { nome: 'MACHADO', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 294.74, peso: 8 },
  { nome: 'MACHADINHA', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 105.6, peso: 5 },
  { nome: 'MACHETE', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 110.53, peso: 6 },
  { nome: 'TASER', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 43.5, peso: 2 },
  { nome: 'RIFLE M4 CARBINE (5.56MM)', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 378.95, peso: 8 },
  { nome: 'PISTOLA DESERT EAGLE (.50 AE)', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 215.79, peso: 6 },
  { nome: 'PISTOLA GLOCK 17 (9MM)', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 260.79, peso: 5 },
  { nome: 'SHOTGUN', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 473.68, peso: 9 },
  { nome: 'REVÓLVER MAGNUM .44', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 233.22, peso: 6 },
  { nome: 'PISTOLA TAURUS PT 1911 (45 ACP)', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 204.26, peso: 5 },
  { nome: 'RIFLE AK-47 (7.62MM)', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 442.11, peso: 8 },
  { nome: 'ESPINGARDA (12 GAUGE)', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 503.98, peso: 10 },
  { nome: 'GRANADA DE MÃO', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 54.5, peso: 3 },
  { nome: 'BOMBA MOLOTOV', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 30.5, peso: 5 },
  { nome: 'ESCUDO BALÍSTICO', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 263.16, peso: 40 },
  { nome: 'COLETE À PROVA DE BALAS', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 3947.37, peso: 4 },
  { nome: 'MUNIÇÃO DIVERSA (30 UND)', grupo: 'COMBATE E DEFESA', categoria: 'equipamento', preco: 100.0, peso: 5 },
  { nome: 'MALETA DE FERRAMENTAS', grupo: 'FERRAMENTAS E TECH', categoria: 'equipamento', preco: 110.47, peso: 5 },
  { nome: 'SERRA ELÉTRICA', grupo: 'FERRAMENTAS E TECH', categoria: 'equipamento', preco: 290.45, peso: 8 },
  { nome: 'BINÓCULOS', grupo: 'FERRAMENTAS E TECH', categoria: 'equipamento', preco: 78.95, peso: 3 },
  { nome: 'NOTEBOOK DELL', grupo: 'FERRAMENTAS E TECH', categoria: 'equipamento', preco: 2494.7, peso: 4 },
  { nome: 'DRONE', grupo: 'FERRAMENTAS E TECH', categoria: 'equipamento', preco: 3088.16, peso: 4 },
];

/** Agrupamentos impressos, na ordem do PDF. */
export const GRUPOS_DO_CATALOGO = ['TRANSTORNOS PSICOLÓGICOS', 'DOENÇAS NEUROLÓGICAS E FÍSICAS', 'INFECÇÕES, FERIMENTOS E SUPORTE MÉDICO', 'MEDKIT', 'BÁSICOS', 'COMBATE E DEFESA', 'FERRAMENTAS E TECH'] as const;
